on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    name: test and coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.3"

      - name: Run Test
        run: |
          go test ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
